"""adding a random model field

Revision ID: 04934c414cfd
Revises: a1e762595051
Create Date: 2024-10-28 03:14:20.596453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04934c414cfd'
down_revision: Union[str, None] = 'a1e762595051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('random', sa.String(length=500), server_default='random entry', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'random')
    # ### end Alembic commands ###
