"""removing the random field

Revision ID: ac4f25ec96f8
Revises: 88de2db27266
Create Date: 2024-10-28 12:10:43.076548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4f25ec96f8'
down_revision: Union[str, None] = '88de2db27266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'random')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('random', sa.VARCHAR(length=500), server_default=sa.text("'random entry'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
