"""swapping fields in users

Revision ID: e2ff08621ec5
Revises: ac4f25ec96f8
Create Date: 2024-10-28 13:09:21.264272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ff08621ec5'
down_revision: Union[str, None] = 'ac4f25ec96f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
